package com.app.raghu.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.app.raghu.entity.User;
import com.app.raghu.payload.UserRequest;
import com.app.raghu.payload.UserResponse;
import com.app.raghu.service.IUserService;
import com.app.raghu.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {

	@Autowired
	private IUserService service;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Autowired
	private JwtUtil jwtUtil;
	
	@PostMapping("/save")
	public ResponseEntity<String> createUser(
			@RequestBody User user
			) 
	{
		Integer id = service.saveUser(user);
		return ResponseEntity.ok("User Created : " + id);
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request) 
	{
		//This code Reads un,pwd from client and tries to validate by checking
		// using userdetails service for token generation
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						request.getUsername(), request.getPassword()
						)
				);
		
		String token = jwtUtil.generateToken(request.getUsername());
		return ResponseEntity.ok(new UserResponse(token, "Generated By Mr. RAGHU"));
	}
	
	
	@PostMapping("/welcome")
	public ResponseEntity<String> showUserData(Principal principal) {
		System.out.println(principal);
		System.out.println(principal.getClass().getName());
		return ResponseEntity.ok("Hello : " + principal.getName());
	}
	
}
